name: GitOps Deploy

on:
  push:
    branches:
      - gitops

permissions:
  contents: read
  id-token: write

env:
  AWS_REGION: us-east-1

  FRONTEND_REPO: 550054567146.dkr.ecr.us-east-1.amazonaws.com/devops-frontend
  BACKEND_REPO: 550054567146.dkr.ecr.us-east-1.amazonaws.com/devops-backend

  ECS_CLUSTER: devops-challenge-cluster
  FRONTEND_SERVICE: devops-challenge-frontend
  BACKEND_SERVICE: devops-challenge-backend

jobs:
  deploy:
    name: Build and Deploy to AWS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::550054567146:role/Github_branch
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build frontend Docker image
        run: |
          docker build \
            --platform linux/amd64 \
            -t ${{ env.FRONTEND_REPO }}:latest \
            ./frontend

      - name: Build backend Docker image
        run: |
          docker build \
            --platform linux/amd64 \
            -t ${{ env.BACKEND_REPO }}:latest \
            ./backend

      - name: Push frontend image to ECR
        run: |
          docker push ${{ env.FRONTEND_REPO }}:latest

      - name: Push backend image to ECR
        run: |
          docker push ${{ env.BACKEND_REPO }}:latest

      - name: Deploy frontend to ECS
        run: |
          aws ecs update-service \
            --cluster "${{ env.ECS_CLUSTER }}" \
            --service "${{ env.FRONTEND_SERVICE }}" \
            --force-new-deployment \
            --region "${{ env.AWS_REGION }}"

      - name: Deploy backend to ECS
        run: |
          aws ecs update-service \
            --cluster "${{ env.ECS_CLUSTER }}" \
            --service "${{ env.BACKEND_SERVICE }}" \
            --force-new-deployment \
            --region "${{ env.AWS_REGION }}"